apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bar
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.slack: idp-notification-test
spec:
  # Project description
  description: bar project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc

