apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar1-echo
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: bar1-echo
  template:
    metadata:
      labels:
        app: bar1-echo
    spec:
      containers:
      - name: bar1-echo
        image: ealen/echo-server:0.9.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "50m"
