apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: go-app-analysis-template
spec:
  args:
  # required in Rollout due to no default value
  - name: service-name
  # optional in Rollout given the default value
  - name: api-url
    value: http://example/measure
  metrics:
  - name: webmetric
    successCondition: response.code == 200
    interval: 10s
    count: 2
    failureLimit: 3
    provider:
      web:
        # placeholders are resolved when an AnalysisRun is created
        url: "{{ args.api-url }}?service={{ args.service-name }}"
        # headers:
        #   - key: Authorization
        #     value: "Bearer {{ args.api-token }}"
        # jsonPath: "{$.results.ok}"