apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 1m
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 90
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local
        query: |
          100 * (
            sum(increase(promhttp_metric_handler_requests_total{job="go-app",code="200"}[1m]))
              /
            sum(increase(promhttp_metric_handler_requests_total{job="go-app"}[1m]))
          )
