apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: daidaovan/go-app:v2.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
  strategy:
    # canary:
    #   steps:
    #   - setWeight: 20
    #   - pause: {}
    #   - setWeight: 40
    #   - pause: {duration: 10}
    #   - setWeight: 60
    #   - pause: {duration: 10}
    #   - setWeight: 80
    #   - pause: {duration: 10}
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 2 # delay starting analysis run until setWeight: 40%
      steps:
      - setWeight: 20
      - pause: {duration: 2m}
      - setWeight: 40
      - pause: {duration: 2m}
      - setWeight: 60
      - pause: {duration: 2m}
      - setWeight: 80
      - pause: {duration: 2m}
