apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-app
  namespace: services
  labels:
    team: monitor-enable
spec:
  selector:
    matchLabels:
      app: go-app
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    any: true
